Gemfile
Rakefile
metadata.json

Request to review the small fix for fixing Jenkin pipeline warnings.

(fix warnings on jenkin pipeline)

---

CHANGELOG.md
metadata.json

This is the PR to merge release 0.1.3 back to master

release prep for 0.1.3

---

spec/acceptance/nodesets/pooler/centos7.yml
spec/spec_helper_acceptance.rb

Request to review the changes for helm acceptance tests to run on centos (vmpooler)

Centosfixhelm

---

manifests/chart_update.pp
manifests/helm_init.pp
spec/spec_helper_acceptance.rb

Request to review the small change for the spec helper update with new parameter for kube_tool

(spec_helper fix)

---

.rubocop.yml
.travis.yml
Gemfile
Rakefile
lib/puppet/parser/functions/helm_chart_update_flags.rb
lib/puppet/parser/functions/helm_create_flags.rb
lib/puppet/parser/functions/helm_delete_flags.rb
lib/puppet/parser/functions/helm_init_flags.rb
lib/puppet/parser/functions/helm_install_flags.rb
lib/puppet/parser/functions/helm_ls_flags.rb
lib/puppet/parser/functions/helm_package_flags.rb
lib/puppet/parser/functions/helm_repo_add_flags.rb
lib/puppet/parser/functions/helm_repo_remove_flags.rb
lib/puppet/parser/functions/helm_repo_update_flags.rb
metadata.json

Request to review the fix for rubocop errors and added gems and dependencies for i18n
https://confluence.puppetlabs.com/display/systemsEngineering/How+to+Prepare+Your+Module+for+Translation
Executed unit tests and acceptance tests successfully

(CLOUD-1602) Fix rubocop error updategemsfori18n

---

.fixtures.yml
.travis.yml
Gemfile
manifests/binary.pp
manifests/chart.pp
manifests/chart_update.pp
manifests/init.pp

Actually run the tests

---

.travis.yml

Request to review the puppet lint job addition to travis

(enabling puppet-lint job on travis)

---

spec/spec_helper_acceptance.rb

Request to review the small changes for spec_helper.

(fix for spec_helper for kube_tool)

---

.rubocop.yml
.rubocop_todo.yml
.sync.yml
.travis.yml
Gemfile
Rakefile
metadata.json
spec/classes/config_spec.rb
spec/default_facts.yml
spec/spec_helper.rb

This PR is to make the Helm module PDK compliant. I have verified that all tests etc are passing for both old and new commands.

Enabling PDK compliance

---

CHANGELOG.md
metadata.json

This PR is to merge the 1.1.0 release branch back into master.

merging 1.1.0 release branch back into master. 

---

README.md

Restructured readme and checked values for the archive_baseurl, proxy, and path parameters.

(CLOUD-2239) Readme updates

---

spec/acceptance/helm_spec.rb
spec/spec_helper_acceptance.rb

Request to review the changes
- Upgraded the k8,golang version
- Added configuration to spec_helper.
**Helm Acceptance test Results**
`the helm module
kubernetes class
it should install the module
localhost $ scp /var/folders/4v/p90k7dqd65348jw6l6xrppdw0000gq/T/beaker20190425-40461-kwz7or ubuntu-1604-master:/tmp/apply_manifest.pp.3tZXyj {:ignore => }
should run
should install kubectl
should install kube-dns
helm class
it should install the module
localhost $ scp /var/folders/4v/p90k7dqd65348jw6l6xrppdw0000gq/T/beaker20190425-40461-1mooxkz ubuntu-1604-master:/tmp/apply_manifest.pp.rscgf6 {:ignore => }
should run
should install helm
it should install the module
localhost $ scp /var/folders/4v/p90k7dqd65348jw6l6xrppdw0000gq/T/beaker20190425-40461-1jkt73t …

MODULES-8946 fix helm testcases

---

lib/puppet/parser/functions/helm_init_flags.rb

Request for a review
Fix helm init flag "--tls-ca-cert"
https://github.com/puppetlabs/puppetlabs-helm/issues/73

MODULES-9237 (Fix helm init flag)

---

README.md
lib/puppet/parser/functions/helm_repo_add_flags.rb
manifests/repo.pp
spec/defines/repo_spec.rb

Adding username/password to let the possibility to authenticate to an external helm repository.

add username and password flags in helm_repo_add_flags

---

manifests/account_config.pp
spec/classes/account_config_spec.rb

Currently if yaml is updated, the new files are not applied.

Use subscribe instead of require to gain autoupdating

---

spec/spec_helper_acceptance.rb

MODULES-10159 remove the pip

---

.sync.yml
.travis.yml
Rakefile
metadata.json
spec/spec_helper.rb

"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`

(IAC-365) updating tokens and dataset for honeycomb

---

README.md
manifests/config.pp
spec/classes/config_spec.rb
spec/spec_helper_acceptance_local.rb

Removal of any offensive or inappropriate terminology from the codebase

(IAC-989) - Removal of Inappropriate Terminology

---

.github/workflows/auto_release.yml
.github/workflows/integration_test.yml
Gemfile
metadata.json
spec/spec_helper_acceptance_local.rb

PDK Update for auto release prep workflow
pdk version: `1.18.1`

pdksync - PDK Update for auto release prep workflow

---

.devcontainer/README.md
.devcontainer/devcontainer.json
.github/workflows/auto_release.yml
.github/workflows/spec.yml
Gemfile
Rakefile
metadata.json

pdksync_heads/main-0-gf3911d3
pdk version: `2.3.0`

pdksync - pdksync_heads/main-0-gf3911d3
